# Generated by Django 5.1.1 on 2024-09-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to='resized_images/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('aspect_ratio_locked', models.BooleanField(default=False)),
            ],
        ),
    ]
